<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"计划实施类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryJihuashishi"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"项目类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryXiangmu"
                    }

                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"教师管理",
                        "menuJump":"列表",
                        "tableName":"jiaoshi"
                    }
                ],
                "menu":"教师管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"xuesheng"
                    }
                ],
                "menu":"学生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"项目管理",
                        "menuJump":"列表",
                        "tableName":"xiangmu"
                    }
                ],
                "menu":"项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"项目计划实施管理",
                        "menuJump":"列表",
                        "tableName":"jihuashishi"
                    }
                ],
                "menu":"项目计划实施管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"项目结题管理",
                        "menuJump":"列表",
                        "tableName":"jieti"
                    }
                ],
                "menu":"项目结题管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"学生管理",
                        "menuJump":"列表",
                        "tableName":"xuesheng"
                    }
                ],
                "menu":"学生管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "审核"
                        ],
                        "menu":"项目管理",
                        "menuJump":"列表",
                        "tableName":"xiangmu"
                    }
                ],
                "menu":"项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"项目计划实施管理",
                        "menuJump":"列表",
                        "tableName":"jihuashishi"
                    }
                ],
                "menu":"项目计划实施管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"项目结题管理",
                        "menuJump":"列表",
                        "tableName":"jieti"
                    }
                ],
                "menu":"项目结题管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"教师",
        "tableName":"jiaoshi"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"项目管理",
                        "menuJump":"列表",
                        "tableName":"xiangmu"
                    }
                ],
                "menu":"项目管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增"
                        ],
                        "menu":"项目计划实施管理",
                        "menuJump":"列表",
                        "tableName":"jihuashishi"
                    }
                ],
                "menu":"项目计划实施管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"项目结题管理",
                        "menuJump":"列表",
                        "tableName":"jieti"
                    }
                ],
                "menu":"项目结题管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"学生",
        "tableName":"xuesheng"
    }
];

var hasMessage = '';
